//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

public static class GeneralFormulas
	{
		const int _MinAgroLevel = 10;
		const int _MaxAgroLevel = 90;
		public static int GetAggressionValue()
		{
			return Random.Range(0,100);
		}
		public static bool isAgrression(int aggressionLevel){
			 if (aggressionLevel > _MaxAgroLevel)
				aggressionLevel = _MaxAgroLevel;
			if (aggressionLevel < _MinAgroLevel)
				aggressionLevel = _MinAgroLevel;
		return aggressionLevel>GetAggressionValue () ;
		}
	}

